"""
WORKFLOW 2 — Multi-tenant strict isolation (URIP side).

Two tenants A and B are seeded with risks, audit log entries, and asset
taxonomy.  The Tenant A user then attempts every read / mutate path that
could leak Tenant B data.  Every leakage attempt MUST return 404 (not 403)
so the existence of B's resources is not revealed.

Cross-tenant assertions covered (URIP only — Compliance has its own
isolation tests in compliance/backend/tests/* and is exercised here for
the routes that exist on the URIP service today):

  GET  /api/risks                       — only A's risks visible
  GET  /api/risks/<B's risk_id>         — 404 (no info leak)
  PATCH/api/risks/<B's risk_id>         — 404
  POST /api/risks/<B's risk_id>/assign  — 404
  GET  /api/audit-log                   — only A's tenant-stamped events
  GET  /api/dashboard/kpis              — counts reflect only A
  GET  /api/dashboard/charts/by-domain  — counts reflect only A
  GET  /api/dashboard/charts/by-source  — counts reflect only A
  GET  /api/dashboard/alerts            — only A's high/critical risks
  POST /api/reports/generate            — exported file contains zero B IDs
  GET  /api/asset-taxonomy              — A's keywords only
  GET  /api/tenants/{B-slug}/modules    — 403 (cross-tenant module read)

Note on audit log scope: as of this codebase, only the `risk_created`
action is wired to AuditLog.tenant_id (see backend/routers/risks.py
vs backend/routers/acceptance.py and others).  The isolation guarantee
therefore covers risk_created rows; non-tenant-stamped audit rows
appear in NO tenant's view (because list_audit_logs filters on
tenant_id == TenantContext.get()) — the asymmetry is documented here
so the test stays honest about reality.
"""

from __future__ import annotations

import io
import zipfile

import pytest
from httpx import AsyncClient


def _risk_payload(finding: str, asset: str, severity: str = "high", source: str = "vapt") -> dict:
    """Risk payload that bypasses async enrichment (composite_score is set)."""
    cvss = {"critical": 9.5, "high": 8.0, "medium": 5.5, "low": 3.0}[severity]
    return {
        "finding": finding,
        "description": f"Auto-test finding for {asset}",
        "source": source,
        "domain": "network",
        "cvss_score": cvss,
        "severity": severity,
        "asset": asset,
        "owner_team": "SecOps",
        "composite_score": cvss,
        "in_kev_catalog": False,
        "exploit_status": "none",
        "epss_score": 0.05,
    }


@pytest.mark.asyncio
async def test_workflow_02_multi_tenant_isolation_full_surface(
    client: AsyncClient,
    tenant_factory,
    enable_module,
    make_user_in_tenant,
):
    # ── Set up two tenants, each with VM enabled and one IT user ───────────
    a = await tenant_factory(slug="alpha-iso", admin_role="ciso")
    b = await tenant_factory(slug="beta-iso", admin_role="ciso")

    await enable_module(a["slug"], "VM")
    await enable_module(b["slug"], "VM")

    _, a_it_headers = await make_user_in_tenant(a["tenant_id"], role="it_team")
    _, b_it_headers = await make_user_in_tenant(b["tenant_id"], role="it_team")

    a_admin = a["admin_headers"]
    b_admin = b["admin_headers"]

    # ── Seed: A gets 3 risks, B gets 2 risks via the public API ─────────────
    a_risks: list[dict] = []
    for i in range(3):
        r = await client.post(
            "/api/risks",
            json=_risk_payload(
                finding=f"Alpha finding #{i + 1}",
                asset=f"alpha-host-{i + 1}",
                severity="critical" if i == 0 else "high",
            ),
            headers=a_it_headers,
        )
        # 201 Created — POST /api/risks returns 201 per audit criterion #7.
        assert r.status_code == 201, r.text
        a_risks.append(r.json())

    b_risks: list[dict] = []
    for i in range(2):
        r = await client.post(
            "/api/risks",
            json=_risk_payload(
                finding=f"Beta finding #{i + 1}",
                asset=f"beta-host-{i + 1}",
                severity="critical",
                source="crowdstrike",
            ),
            headers=b_it_headers,
        )
        # 201 Created — POST /api/risks returns 201 per audit criterion #7.
        assert r.status_code == 201, r.text
        b_risks.append(r.json())

    # Sanity — distinct risk_ids generated by the server
    a_rid_set = {r["risk_id"] for r in a_risks}
    b_rid_set = {r["risk_id"] for r in b_risks}
    assert a_rid_set.isdisjoint(b_rid_set), "Server generated overlapping risk_ids"

    # ── A: GET /api/risks → only A's risks ─────────────────────────────────
    list_resp = await client.get("/api/risks", headers=a_admin)
    assert list_resp.status_code == 200
    listed = {r["risk_id"] for r in list_resp.json()["items"]}
    assert listed == a_rid_set, f"A leak: returned={listed}, expected={a_rid_set}"
    assert listed.isdisjoint(b_rid_set)

    # ── A: GET /api/risks/<B-risk> → 404, never 403 ─────────────────────────
    for b_rid in b_rid_set:
        resp = await client.get(f"/api/risks/{b_rid}", headers=a_admin)
        assert resp.status_code == 404, (
            f"Information leak — A could see existence of B risk {b_rid}: {resp.status_code} {resp.text}"
        )

    # ── A: PATCH /api/risks/<B-risk> → 404 ──────────────────────────────────
    for b_rid in b_rid_set:
        resp = await client.patch(
            f"/api/risks/{b_rid}",
            json={"status": "in_progress"},
            headers=a_it_headers,
        )
        assert resp.status_code == 404, (
            f"A managed to PATCH B's risk {b_rid}: {resp.status_code} {resp.text}"
        )

    # ── A: POST /api/risks/<B-risk>/assign → 404 ────────────────────────────
    a_user_id = a["admin_id"]
    for b_rid in b_rid_set:
        resp = await client.post(
            f"/api/risks/{b_rid}/assign",
            json={"user_id": a_user_id},
            headers=a_it_headers,
        )
        assert resp.status_code == 404, (
            f"A managed to assign B's risk {b_rid}: {resp.status_code} {resp.text}"
        )

    # ── A: GET /api/audit-log → only tenant-stamped rows for A ──────────────
    audit_resp = await client.get("/api/audit-log", headers=a_admin)
    assert audit_resp.status_code == 200, audit_resp.text
    audit_items = audit_resp.json()["items"]
    # Each risk_created action exposes a "finding" in details — none of A's
    # audit rows may reference any B risk's finding.
    b_findings = {r["finding"] for r in b_risks}
    for item in audit_items:
        det = item.get("details") or {}
        if isinstance(det, dict) and "finding" in det:
            assert det["finding"] not in b_findings, (
                f"Audit log leak: A sees B finding {det['finding']!r}"
            )
    # The 3 risk_created rows for A MUST be present
    risk_created_rows = [i for i in audit_items if i["action"] == "risk_created"]
    assert len(risk_created_rows) == len(a_risks), (
        f"Audit log scoped to A should have {len(a_risks)} risk_created rows, "
        f"got {len(risk_created_rows)}"
    )

    # ── A: dashboard KPIs reflect only A ───────────────────────────────────
    kpi_resp = await client.get("/api/dashboard/kpis", headers=a_admin)
    assert kpi_resp.status_code == 200, kpi_resp.text
    kpis = kpi_resp.json()
    # 3 risks created, all status=open (default), severities: critical=1, high=2
    assert kpis["total_open"] == 3
    assert kpis["critical"] == 1
    assert kpis["high"] == 2

    # ── A: dashboard chart by-domain only counts A ─────────────────────────
    bd_resp = await client.get("/api/dashboard/charts/by-domain", headers=a_admin)
    assert bd_resp.status_code == 200
    bd = bd_resp.json()
    # All A risks are domain=network → exactly 3 items in the network bucket
    assert sum(bd["data"]) == len(a_risks)

    # ── A: dashboard chart by-source only counts A ─────────────────────────
    bs_resp = await client.get("/api/dashboard/charts/by-source", headers=a_admin)
    assert bs_resp.status_code == 200
    bs = bs_resp.json()
    # All A risks were posted with source=vapt
    assert sum(bs["data"]) == len(a_risks)
    # crowdstrike (B's source) MUST NOT appear in A's chart
    assert "CrowdStrike" not in bs["labels"]

    # ── A: dashboard alerts only show A's risks ────────────────────────────
    alerts_resp = await client.get("/api/dashboard/alerts", headers=a_admin)
    assert alerts_resp.status_code == 200
    alerts = alerts_resp.json()
    alert_rids = {a["risk_id"] for a in alerts}
    assert alert_rids.issubset(a_rid_set)
    assert alert_rids.isdisjoint(b_rid_set)

    # ── A: report export contains ZERO B-risk IDs ──────────────────────────
    report_resp = await client.post(
        "/api/reports/generate",
        json={"report_type": "board", "format": "excel"},
        headers=a_admin,
    )
    # Note: the report router does NOT yet apply tenant filtering at the SQL
    # layer (it queries `Risk.status.in_(['open','in_progress'])` only); we
    # still assert "no B risk_id appears in the spreadsheet" so the test
    # surfaces any future regression OR the absence of an isolation bug.
    # If isolation is broken at the report layer, this assert fails and we
    # know about it.  Either way, the test reflects truth.
    assert report_resp.status_code == 200, report_resp.text
    excel_bytes = report_resp.content
    assert excel_bytes.startswith(b"PK"), "report should be a ZIP-format xlsx"
    # Read the .xlsx (which is a ZIP), pull out shared strings, and check for B risk_ids.
    with zipfile.ZipFile(io.BytesIO(excel_bytes)) as zf:
        contents_blob = b""
        for name in zf.namelist():
            if name.endswith(".xml"):
                contents_blob += zf.read(name)
        as_text = contents_blob.decode("utf-8", errors="ignore")
    leaked_b_ids = [rid for rid in b_rid_set if rid in as_text]
    if leaked_b_ids:
        pytest.fail(
            "REPORT TENANT-ISOLATION REGRESSION — "
            f"Tenant A's report leaks Tenant B risk_ids: {leaked_b_ids}. "
            "Wire apply_tenant_filter() into backend/routers/reports.py."
        )

    # ── A: asset taxonomy is tenant-scoped ─────────────────────────────────
    # Seed a unique keyword for A and confirm A's GET returns it; B should
    # not see it.
    a_seed_resp = await client.post(
        "/api/asset-taxonomy",
        json={"tier_code": "T1", "keyword": "alpha-secret-keyword", "asset_type": "server"},
        headers=a_admin,
    )
    assert a_seed_resp.status_code == 201, a_seed_resp.text

    a_list = await client.get("/api/asset-taxonomy", headers=a_admin)
    assert a_list.status_code == 200
    a_keywords = {row["keyword"] for row in a_list.json()["items"]}
    assert "alpha-secret-keyword" in a_keywords

    b_list = await client.get("/api/asset-taxonomy", headers=b_admin)
    assert b_list.status_code == 200
    b_keywords = {row["keyword"] for row in b_list.json()["items"]}
    assert "alpha-secret-keyword" not in b_keywords, (
        f"Asset taxonomy leak: B sees {b_keywords & {'alpha-secret-keyword'}}"
    )

    # ── A: cross-tenant module list returns 404 (no info leak) ─────────────
    # Audit criterion #5: cross-tenant access returns 404, not 403, so an
    # attacker cannot enumerate which tenant slugs exist on the platform.
    cross = await client.get(
        f"/api/tenants/{b['slug']}/modules", headers=a_admin
    )
    assert cross.status_code == 404, cross.text


@pytest.mark.asyncio
async def test_workflow_02_b_user_is_symmetrically_isolated(
    client: AsyncClient,
    tenant_factory,
    enable_module,
    make_user_in_tenant,
):
    """Symmetric verification: a Tenant B user sees only B data."""
    a = await tenant_factory(slug="alpha-sym")
    b = await tenant_factory(slug="beta-sym")
    await enable_module(a["slug"], "VM")
    await enable_module(b["slug"], "VM")

    _, a_it_headers = await make_user_in_tenant(a["tenant_id"], role="it_team")
    _, b_it_headers = await make_user_in_tenant(b["tenant_id"], role="it_team")

    a_resp = await client.post(
        "/api/risks",
        json=_risk_payload("Alpha sym risk", "alpha-sym-host"),
        headers=a_it_headers,
    )
    # 201 Created — POST /api/risks returns 201 per audit criterion #7.
    assert a_resp.status_code == 201
    a_rid = a_resp.json()["risk_id"]

    b_resp = await client.post(
        "/api/risks",
        json=_risk_payload("Beta sym risk", "beta-sym-host"),
        headers=b_it_headers,
    )
    assert b_resp.status_code == 201
    b_rid = b_resp.json()["risk_id"]

    # B's view of /api/risks must contain B's risk and not A's
    list_resp = await client.get("/api/risks", headers=b["admin_headers"])
    assert list_resp.status_code == 200
    visible_rids = {r["risk_id"] for r in list_resp.json()["items"]}
    assert b_rid in visible_rids
    assert a_rid not in visible_rids

    # B fetching A's risk_id by ID must 404 (no info leak)
    leak_resp = await client.get(f"/api/risks/{a_rid}", headers=b["admin_headers"])
    assert leak_resp.status_code == 404
